name: DungeonAPI
authors: [Zeryther]
website: https://wrathofdungeons.net
version: 1.0
main: net.wrathofdungeons.dungeonapi.DungeonAPI
softdepend: [HolographicDisplays]

commands:
  mbchat:
    description: mbchat